project_id = "epbpclslyrphcqmlfiin"

[functions.send-free-lead-notification]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = false

[functions.generate-database-csv]
verify_jwt = false

[functions.process-database-purchase]
verify_jwt = false